version: '3.8'

services:
 db_marvel:
    container_name: "db_marvel"
    image: "postgres:alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=api
      - POSTGRES_DB=marvelComics